version: '3.2'

services:
  db:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "PasswordAzure@123!"
    ports:
      - "9433:1433"
  test:
    image: sql-test-ps:linux
    depends_on:
      - db
    restart: on-failure
    build:
      context: .
      dockerfile: linux.Dockerfile
    environment:
      CONNECTIONSTRING: "Data Source=db,1433;Initial Catalog=master;User ID=sa;Password=PasswordAzure@123!"